export const SYSTEM_FUNCTIONS_PREFIX = '/system-functions'
export const SYSTEM_APPLICATIONS_PREFIX = '/system-applications'
export const SYSTEM_TOOLS_PREFIX = '/system-tools'
export const UNIVERSAL_COMPONENTS_PREFIX = '/universal-components'
export const BUILTIN_COMPONENTS_PREFIX = '/builtin-components'
export const ERROR_PAGES_PREFIX = '/error-pages'
export const WEBSITE_ANALYTICS_PREFIX = '/website-analytics'
