export const userColumnsI18nKeyMap = new Map([
  ['avatar', 'User.Avatar'],
  ['username', 'User.Username'],
  ['phoneNumber', 'User.PhoneNumber'],
  ['email', 'User.Email'],
  ['name', 'User.Name'],
  ['lastName', 'User.LastName'],
  ['firstName', 'User.FirstName'],
  ['nickName', 'User.NickName'],
  ['genderLabel', 'User.Gender'],
  ['birthDate', 'User.BirthDate'],
  ['country', 'User.Country'],
  ['province', 'User.Province'],
  ['city', 'User.City'],
  ['address', 'User.Address'],
  ['biography', 'User.Biography'],
  ['verified', 'UserManagement.VerifyOrNot'],
  ['enabled', 'UserManagement.EnableOrNot'],
  ['createdAt', 'UserManagement.EnterTime'],
  ['roles', 'User.Roles'],
  ['authTypes', 'User.AuthType'],
  ['operation', 'Common.Operation']
])
